class Pin < ActiveRecord::Base
  attr_accessible :description, :image
  #Validates a pin before it can be created. At least must be present, etc.
  #See more validations at rails validations on google

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  														 content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
  														 size: { less_than: 5.megabytes } 
  #Make sure an image is there, in which format, and size.
  #different relationships at rails associtaions
  #An assocication generated by paperclip to allow attaching things.
  #Paper clip allows you to style the image, see below.
  has_attached_file :image, styles: { medium: "320x240>"}
  belongs_to :user
 
end
